@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Play game

loop until winner found
alt programming phase
Client -> Server: Patch (player mat, ready)
Client -> Server: Get allPlayersReady
Server --> Client: Return allPlayersReady
alt all players are ready
Client -> Server: Patch (phase status)
end
end

alt activation phase & \nafter current players turn
Client -> Server: Put (game state)
end
end

@enduml