@startuml
'https://plantuml.com/sequence-diagram
hide footbox

autonumber
title Setup new game

Client -> Server: Post (gameStateTemplate)
Client <-- Server: response
alt response =created
    Client -> Client: joinGame
else response != create
    Client-> Client: showError
end
@enduml